// DO NOT EDIT BY HAND. Generated by ../version.py.

#ifndef VERSION_H
#define VERSION_H

#define APP_VER_MAJOR    2
#define APP_VER_MINOR    0
#define APP_VER_REVISION 9
#define APP_VER_BUILD    1

#define APP_VER_SHORT "2.0.9.1"
#define APP_VER_FULL  "2.0 Dev 9a (Gavrant)"

#define APP_GIT_BUILD "d7ac840"

#define APP_COMPANY   "NifTools"
#define APP_NAME      "NifSkope"
#define APP_NAME_FULL "NifSkope 2.0 Dev 9a (Gavrant)"

#endif // VERSION_H
